🔀 :: (#26) 레디스 엔티티 들들들
Software-Meister-High-School-Community/MOIZA-Spring-Server pull request #46
Opened 2022-03-15 10:49 UTC by glay415

2022-03-15 10:52 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/domain/auth/entity/EmailCode.java
> +	@Id
해당 어노테이션은 jpa에서 사용하는 어노테이션입니다.
org.springframework.data.annotation.Id로 변경 부탁드립니다.

2022-03-15 11:05 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/domain/auth/entity/RefreshToken.java
> +		this.timeToLive = timeToLive;
해당 redis 객체는 refresh token을 발급할 때만 사용될 것 같은데 timeToLive를 파라미터로 받지말고 바로 값을 넣어주는 것은 어떨까요?

2022-03-15 11:05 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/domain/auth/type/Type.java
> +public enum Type {
엄?

2022-03-15 11:06 UTC, glay415 commented on src/main/java/com/example/moizaspringserver/domain/auth/entity/RefreshToken.java
> +		this.timeToLive = timeToLive;
그걸 어케해요?

2022-03-15 11:07 UTC, lyutvs commented on src/main/java/com/example/moizaspringserver/domain/auth/type/Type.java
> +public enum Type {
엄

2022-03-15 11:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/domain/auth/entity/RefreshToken.java
> +		this.timeToLive = timeToLive;
```suggestion
		this.timeToLive = 시간;
```
이런식으로 하면 되지 않을까요?

2022-03-16 00:09 UTC, VINTO1819 requested changes

2022-03-16 00:09 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/domain/viewcount/entity/FeedViewCount.java
> +		this.viewCount = viewCount;
`viewCount`는 초기에는 항상 0으로 생성될텐데, 인자로 받지 말고 0으로 초기화해도 괜찮을 거 같습니다.
ERD에서도 default value는 0으로 되어있네요

2022-03-16 00:10 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/domain/viewcount/entity/FeedViewCount.java
> +		this.viewCount = viewCount;
`viewCount`는 초기에는 항상 0으로 생성될텐데, 인자로 받지 말고 0으로 초기화해도 괜찮을 거 같습니다.
ERD에서도 default value는 0으로 되어있네요

2022-03-16 00:47 UTC, softpeanut approved these changes

2022-03-16 01:30 UTC, VINTO1819 approved these changes

2022-03-16 01:49 UTC, lyutvs approved these changes

2022-03-16 05:19 UTC, merged