🔀 :: (#48) security 설정
Software-Meister-High-School-Community/MOIZA-Spring-Server pull request #52
Opened 2022-03-17 06:13 UTC by lyutvs

close #48

2022-03-17 07:08 UTC, softpeanut requested changes

2022-03-17 07:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .requestMatchers(CorsUtils::isCorsRequest).permitAll()
isCorsRequest가 아니라 preFlight 요청에 대해서 permitAll을 해주는 거에요

2022-03-17 10:11 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .regexMatchers().authenticated();
여기를 anyRequest가 아닌 regexMatchers로 하신 이유가 있나요?

2022-03-17 11:22 UTC, lyutvs commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .regexMatchers().authenticated();
엇 그러네요 굳이 해줄 필요가 없는데

2022-03-17 23:33 UTC, softpeanut approved these changes

2022-03-19 12:09 UTC, glay415 approved these changes

2022-03-19 12:11 UTC, merged

2022-03-19 12:11 UTC, VINTO1819 approved these changes