🔀 :: (#53) JWT 구현
Software-Meister-High-School-Community/MOIZA-Spring-Server pull request #54
Opened 2022-03-24 06:13 UTC by VINTO1819

close #53

2022-03-24 06:16 UTC, VINTO1819 commented
`SecurityConfig.java` 부분에서 이 부분이 맞는지 잘 모르겠네요.. 어떻게 설정하면 될지 리뷰 부탁드립니다
```java
.and()
                .authorizeRequests()
                .antMatchers("/auth/*").anonymous()
                .and()

                .addFilterBefore(new JwtTokenFilter(jwtTokenProvider), UsernamePasswordAuthenticationFilter.class)
                .authorizeRequests()
                .anyRequest()
                .authenticated();
```

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/config/JwtProperties.java
> +@ConfigurationProperties(prefix = "jwt")
prefix에 맞는 yml파일 설정 부탁드립니다

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +    public JwtTokenFilter(JwtTokenProvider jwtTokenProvider) {
Lombok 사용하는 건 어떤가요?

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            if(StringUtils.isEmpty(jwtToken)) request.setAttribute("unauthorization", "token required");
이렇게 request.setAttribute로 예외 처리해주는 것보다 exception filter를 통해서 한 곳에서 예외 처리해주는게 더 나을 것 같아요

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setExpiration(expiresAt)
지금 시작해서 지금 만료되는 건가요..?

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .parseClaimsJws(jwtToken)
반복되는 코드를 따로 메소드로 분리해보는 것도 좋을 것 같습니다

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +    public SecurityConfig(JwtTokenProvider jwtTokenProvider) {
여기도 Lombok 사용하는 게 어때요?

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .antMatchers("/auth/*").anonymous()
익명의 사용자의 접근을 허용한 이유가 있을까요?
전부 허용이라면 permitAll을 사용해도 될 것 같습니다
그리고 /auth/* 이런식으로 *이 하나만 있어도 모든 요청이 잘 걸러지나요?

2022-03-24 08:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .authenticated();
authorizeRequests를 또 사용할거면 위쪽에 붙여서 사용하는게 더 좋을 것 같습니다

2022-03-25 12:38 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            if(StringUtils.isEmpty(jwtToken)) request.setAttribute("unauthorization", "token required");
`CustomException` 기반으로 `UnauthorizedException`을 만들어야 할 거 같은데, 어느 패키지에다 만들면 될까요..?

2022-03-25 12:41 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setExpiration(expiresAt)
만료기간 누락된 문제 해결하겠습니다

2022-03-25 12:44 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .parseClaimsJws(jwtToken)
토큰 파싱 부분은 private 메소드로 분리해보도록 하겠습니다

2022-03-25 14:13 UTC, softpeanut commented
CI 머지되면 마저 하시죠

2022-03-26 01:46 UTC, VINTO1819 commented on build.gradle
> +	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
`@ConfigurationProperties`를 사용할 때 오토컴플릿을 지원하려면 필요하다고 해서 추가했습니다만, 필요없다면 제거하도록 하겠습니다

2022-03-26 01:48 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            else if(!jwtTokenProvider.validation(jwtToken)) request.setAttribute("unauthorization", "invalid or expired token");
그렇다면 Exception Class는 security 패키지 하위에다 작성하면 될까요?

2022-03-26 01:54 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .antMatchers("/auth/*").anonymous()
접근 권한은 permitAll로 변경하고, wildcard 문자는 **로 올바르게 수정하겠습니다

2022-03-27 09:35 UTC, lyutvs commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            else if(!jwtTokenProvider.validation(jwtToken)) request.setAttribute("unauthorization", "invalid or expired token");
그냥 global 에다가 exception 패키지 하나 만들어서 작성 하면 될거 같아요

2022-03-27 12:26 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            else if(!jwtTokenProvider.validation(jwtToken)) request.setAttribute("unauthorization", "invalid or expired token");
exception 패키지 아래에다 추가했습니다

2022-03-27 12:27 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +            if(StringUtils.isEmpty(jwtToken)) request.setAttribute("unauthorization", "token required");
Exception 기반으로 처리하도록 변경했습니다

2022-03-27 23:34 UTC, softpeanut requested changes

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/error/security/NoTokenServedException.java
> +    private static ErrorCode errorCode = new ErrorCode(400, "No token served");
ErrorCode를 enum으로 만들어서 사용하는 이유는 인스턴스 값을 동일하게 사용하려는 것도 있고, 관리 포인트를 한 곳으로 만들기 위해서 이기도 한데, 이렇게 매번 Exception마다 new 키워드를 통해 생성자를 만들면 enum으로 만든 이유가 사라집니다.

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +@AllArgsConstructor
@RequiredArgsConstructor로도 충분할 것 같아요

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +@AllArgsConstructor
여기도 @RequiredArgsConstructor면 될 것 같아요

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/SecurityConfig.java
> +                .anyRequest().authenticated();
이거 위쪽으로 붙이는게 더 깔끔할 것 같아요

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +        if(StringUtils.isEmpty(jwtToken)) throw new NoTokenServedException();
Spring Security에서는 모든 요청이 필터를 거쳐서 들어오게 되는데 토큰이 없는 경우도 있습니다. 그런데 이렇게 토큰이 없을 때 예외를 던지면 안될 것 같습니다.

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/config/JwtProperties.java
> +@Setter
@Setter보다 final 키워드를 붙이고 @RequiredArgsContructor를 사용하는게 더 좋을 것 같아요

2022-03-27 23:34 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +        else if(!jwtTokenProvider.validation(jwtToken)) throw new InvalidTokenException();
해당 validation 메소드에서 직접 예외를 던지는 것이 더 직관적일 것 같아요

2022-03-29 09:22 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/error/security/NoTokenServedException.java
> +    private static ErrorCode errorCode = new ErrorCode(400, "No token served");
현재 ErrorCode 클래스가 enum이 아닌 일반 클래스로 되어있길래 이렇게 구현했습니다만, enum으로 사용할 것을 제안하셨으니 enum으로 바꾼 뒤에 status랑 message를 property로 가지도록 수정하겠습니다.

2022-03-30 07:03 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +@AllArgsConstructor
`@RequiredArgsConstructor`로 변경하겠습니다

2022-04-01 03:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/error/security/InvalidTokenException.java
> +    public InvalidTokenException() { super(ErrorCode.INVALID_TOKEN); }
줄바꿈 해주세요

2022-04-01 03:08 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/filter/JwtTokenFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
Authentication 객체를 security context holder에 넣는 로직도 필요할 것 같습니다.

2022-04-04 23:47 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/error/exception/ErrorCode.java
> +        INVALID_TOKEN(400, "Expired or wrong token served"),
그럼 HTTP status는 401로 변경하도록 하겠습니다

2022-04-04 23:52 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/error/security/InvalidTokenException.java
> +        super(ErrorCode.INVALID_TOKEN);
싱글톤 패턴으로 변경하도록 하겠습니다

2022-04-06 02:45 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenAuthentication.java
> +public class JwtTokenAuthentication extends AbstractAuthenticationToken {
AbstractAuthenticationToken을 상속받아서 따로 이렇게 만들어주는 이유가 있을까요?

2022-04-06 02:48 UTC, softpeanut commented
근데 이거 작동이 잘 되는 거에요?

2022-04-07 04:05 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenAuthentication.java
> +public class JwtTokenAuthentication extends AbstractAuthenticationToken {
JWT도 담을 수 있는 토큰을 구현하기 위해서 상속받은 뒤 별도로 토큰을 구현했습니다

2022-04-07 04:06 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenAuthentication.java
> +public class JwtTokenAuthentication extends AbstractAuthenticationToken {
굳이 안해도 되면 `UserPasswordAuthenticationToken`으로 변경하겠습니다

2022-04-17 11:42 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenAuthentication.java
> +public class JwtTokenAuthentication extends UsernamePasswordAuthenticationToken {
provider 안에서 token 반환하는 방향으로 다시 만들어보겠습니다

2022-04-17 11:42 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenAuthentication.java
> +public class JwtTokenAuthentication extends UsernamePasswordAuthenticationToken {
Authentication 객체도 상속 말고 그냥 `UsernamePasswordAuthenticationToken` 사용하는걸로 바꾸겠습니다

2022-04-17 11:46 UTC, VINTO1819 commented
UserDetail이랑 UserDetailService는 구현이 안되어있어서 principal 넣는 부분은 일단 null처리 했습니다.

2022-04-17 14:15 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +            authentication.setAuthenticated(false);
이 로직이 꼭 필요한 이유가 뭔가요?

2022-04-17 14:15 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +    public String generate(Authentication auth) {
토큰 생성을 위해 Authentication 객체를 따로 불러와서 넣어주는 것보다 매개변수 값으로 auth.getPrincipal 값인 email이나 accountId를 넣어주는 게 더 낳을 것 같아요

2022-04-17 14:15 UTC, softpeanut commented
코드 스멜도 해결해주시고요

2022-04-18 00:29 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +            authentication.setAuthenticated(false);
Token이 안들어온 상황이랑 잘못된 Token이 들어온 상황이랑 분리된 Exception 생성을 염두에 두고 작성했던 코드인데, Authentication 반환으로 코드를 변경했으니 삭제하겠습니다

2022-04-18 01:31 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setSubject(userId + "")
toString을 위해서 표현한 것인가요?

2022-04-18 04:14 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setSubject(userId + "")
네, 필요하다면 valueOf나 toString으로 변경하도록 하겠습니다

2022-04-19 23:32 UTC, VINTO1819 commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setSubject(userId + "")
@softpeanut toString이나 valueOf로 바꿀까요?

2022-04-20 00:39 UTC, softpeanut commented on src/main/java/com/example/moizaspringserver/global/security/JwtTokenProvider.java
> +                .setSubject(userId + "")
toString이 좋을 것 같아요

2022-04-20 05:53 UTC, softpeanut approved these changes

2022-04-20 05:54 UTC, softpeanut commented
시간이 너무 지체되니까 일단 머지하고 오류나면 그 때 수정하죠

2022-04-20 11:03 UTC, lyutvs approved these changes

2022-04-20 11:04 UTC, merged